Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,16 +1,23 @@
-#!/usr/bin/env bash
-#transfers a file from our client to a server:
-#Accepts 4 parameters
-#The path to the file to be transferred
-#The IP of the server we want to transfer the file to
-#The username scp connects with
-#The path to the SSH private key that scp uses
-#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
-#scp must transfer the file to the user home directory ~/
-#Strict host key checking must be disabled when using scp
-if [ $# -lt 4 ]
-then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+#!/bin/bash
+
+# Check if all required parameters are passed
+if [ "$#" -lt 4 ]; then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# Assign parameters to variables
+path_to_file="$1"
+ip="$2"
+username="$3"
+path_to_ssh_key="$4"
+
+# Use scp to transfer the file to the server
+scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~/"
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+  echo "File transfer successful!"
 else
-	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  echo "File transfer failed. Please check the parameters and try again."
 fi
